/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkFileFilter.xs. Do not edit this file, edit GtkFileFilter.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\GtkFileFilter.xs"
/*
 * Copyright (c) 2003 by the gtk2-perl team (see the file AUTHORS)
 *
 * Licensed under the LGPL, see LICENSE file for more information.
 *
 * $Id$
 */

#include "gtk2perl.h"


/*
struct _GtkFileFilterInfo
{
  GtkFileFilterFlags contains;
  
  const gchar *filename;
  const gchar *uri;
  const gchar *display_name;
  const gchar *mime_type;
};
*/

static SV *
newSVGtkFileFilterInfo (const GtkFileFilterInfo * info)
{
	HV * hv;

	if (!info)
		return &PL_sv_undef;

	hv = newHV ();

	gperl_hv_take_sv_s (hv, "contains",
	                    newSVGtkFileFilterFlags (info->contains));
	if (info->filename)
		gperl_hv_take_sv_s (hv, "filename",
		                    gperl_sv_from_filename (info->filename));
	if (info->uri)
		gperl_hv_take_sv_s (hv, "uri",
		                    newSVpv (info->uri, PL_na));
	if (info->display_name)
		gperl_hv_take_sv_s (hv, "display_name",
		                    newSVGChar (info->display_name));
	if (info->mime_type)
		gperl_hv_take_sv_s (hv, "mime_type",
		                    newSVGChar (info->mime_type));

	return newRV_noinc ((SV*) hv);
}

static GtkFileFilterInfo *
SvGtkFileFilterInfo (SV * sv)
{
	HV * hv;
	SV ** svp;
	GtkFileFilterInfo * info;

	if (!gperl_sv_is_hash_ref (sv))
		croak ("invalid file filter info - expecting a hash reference");

	hv = (HV*) SvRV (sv);

	info = gperl_alloc_temp (sizeof (GtkFileFilterInfo));

	if ((svp = hv_fetch (hv, "contains", 8, 0)))
		info->contains = SvGtkFileFilterFlags (*svp);
	if ((svp = hv_fetch (hv, "filename", 8, 0)))
		info->filename = gperl_filename_from_sv (*svp);
	if ((svp = hv_fetch (hv, "uri", 3, 0)))
		info->uri = SvPV_nolen (*svp);
	if ((svp = hv_fetch (hv, "display_name", 12, 0)))
		info->display_name = SvGChar (*svp);
	if ((svp = hv_fetch (hv, "mime_type", 9, 0)))
		info->mime_type = SvGChar (*svp);

	return info;
}

static gboolean
gtk2perl_file_filter_func (const GtkFileFilterInfo *filter_info,
                           gpointer                 data)
{
	GPerlCallback * callback = (GPerlCallback*) data;
	GValue value = {0,};
	gboolean retval;
	SV * sv;
	g_value_init (&value, G_TYPE_BOOLEAN);
	sv = newSVGtkFileFilterInfo (filter_info);
	gperl_callback_invoke (callback, &value, sv);
	retval = g_value_get_boolean (&value);
	SvREFCNT_dec (sv);
	g_value_unset (&value);
	return retval;
}

#line 107 "xs\\GtkFileFilter.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 249 "xs\\GtkFileFilter.c"

XS_EUPXS(XS_Gtk2__FileFilter_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	GtkFileFilter *	RETVAL;

	RETVAL = gtk_file_filter_new(/*void*/);
	ST(0) = newSVGtkFileFilter (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileFilter_set_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_set_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filter, name");
    {
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;
	const gchar *	name;

	/* same as SvGChar(), but not in a function */
	sv_utf8_upgrade (ST(1));
	name = (const gchar *)SvPV_nolen (ST(1))
;

	gtk_file_filter_set_name(filter, name);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileFilter_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filter");
    {
	const gchar *	RETVAL;
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;

	RETVAL = gtk_file_filter_get_name(filter);
	ST(0) = sv_newmortal();
	/* same as newSVGChar(), but not in a function */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileFilter_add_mime_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_add_mime_type)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filter, mime_type");
    {
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;
	const gchar *	mime_type;

	/* same as SvGChar(), but not in a function */
	sv_utf8_upgrade (ST(1));
	mime_type = (const gchar *)SvPV_nolen (ST(1))
;

	gtk_file_filter_add_mime_type(filter, mime_type);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileFilter_add_pattern); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_add_pattern)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filter, pattern");
    {
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;
	const gchar *	pattern;

	/* same as SvGChar(), but not in a function */
	sv_utf8_upgrade (ST(1));
	pattern = (const gchar *)SvPV_nolen (ST(1))
;

	gtk_file_filter_add_pattern(filter, pattern);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileFilter_add_custom); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_add_custom)
{
    dVAR; dXSARGS;
    if (items < 3 || items > 4)
       croak_xs_usage(cv,  "filter, needed, func, data=NULL");
    {
#line 115 "xs\\\\GtkFileFilter.xs"
	GType param_types[1];
	GPerlCallback * callback;
#line 365 "xs\\GtkFileFilter.c"
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;
	GtkFileFilterFlags	needed = SvGtkFileFilterFlags (ST(1))
;
	SV *	func = ST(2)
;
	SV *	data;

	if (items < 4)
	    data = NULL;
	else {
	    data = ST(3)
;
	}
#line 118 "xs\\\\GtkFileFilter.xs"
	param_types[0] = GPERL_TYPE_SV;
	callback = gperl_callback_new (func, data, 1, param_types, G_TYPE_BOOLEAN);
	gtk_file_filter_add_custom (filter, needed,
	                            gtk2perl_file_filter_func, callback,
	                            (GDestroyNotify)gperl_callback_destroy);
#line 386 "xs\\GtkFileFilter.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileFilter_get_needed); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_get_needed)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filter");
    {
	GtkFileFilterFlags	RETVAL;
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;

	RETVAL = gtk_file_filter_get_needed(filter);
	ST(0) = newSVGtkFileFilterFlags (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileFilter_filter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_filter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filter, filter_info");
    {
	gboolean	RETVAL;
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;
	SV *	filter_info = ST(1)
;

	RETVAL = gtk_file_filter_filter(filter, SvGtkFileFilterInfo (filter_info));
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#if GTK_CHECK_VERSION (2, 6, 0)
#define XSubPPtmpAAAA 1


XS_EUPXS(XS_Gtk2__FileFilter_add_pixbuf_formats); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileFilter_add_pixbuf_formats)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filter");
    {
	GtkFileFilter *	filter = SvGtkFileFilter (ST(0))
;

	gtk_file_filter_add_pixbuf_formats(filter);
    }
    XSRETURN_EMPTY;
}

#endif
#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Gtk2__FileFilter); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Gtk2__FileFilter)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Gtk2::FileFilter::new", XS_Gtk2__FileFilter_new, file);
        newXS("Gtk2::FileFilter::set_name", XS_Gtk2__FileFilter_set_name, file);
        newXS("Gtk2::FileFilter::get_name", XS_Gtk2__FileFilter_get_name, file);
        newXS("Gtk2::FileFilter::add_mime_type", XS_Gtk2__FileFilter_add_mime_type, file);
        newXS("Gtk2::FileFilter::add_pattern", XS_Gtk2__FileFilter_add_pattern, file);
        newXS("Gtk2::FileFilter::add_custom", XS_Gtk2__FileFilter_add_custom, file);
        newXS("Gtk2::FileFilter::get_needed", XS_Gtk2__FileFilter_get_needed, file);
        newXS("Gtk2::FileFilter::filter", XS_Gtk2__FileFilter_filter, file);
#if XSubPPtmpAAAA
        newXS("Gtk2::FileFilter::add_pixbuf_formats", XS_Gtk2__FileFilter_add_pixbuf_formats, file);
#endif

    /* Initialisation Section */

#if XSubPPtmpAAAA
#endif
#line 487 "xs\\GtkFileFilter.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

