/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkFileSelection.xs. Do not edit this file, edit GtkFileSelection.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\GtkFileSelection.xs"
/*
 * Copyright (c) 2003 by the gtk2-perl team (see the file AUTHORS)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the 
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330, 
 * Boston, MA  02111-1307  USA.
 *
 * $Id$
 */

#include "gtk2perl.h"

#line 34 "xs\\GtkFileSelection.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 176 "xs\\GtkFileSelection.c"

XS_EUPXS(XS_Gtk2__FileSelection_dir_list); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_dir_list)
{
    dVAR; dXSARGS;
    dXSI32;
    if (items != 1)
       croak_xs_usage(cv,  "fs");
    {
	GtkFileSelection*	fs = SvGtkFileSelection (ST(0))
;
	GtkWidget *	RETVAL;
#line 50 "xs\\\\GtkFileSelection.xs"
	switch (ix) {
		case  0: RETVAL = fs->dir_list;         break;
		case  1: RETVAL = fs->file_list;        break;
		case  2: RETVAL = fs->selection_entry;  break;
		case  3: RETVAL = fs->selection_text;   break;
		case  4: RETVAL = fs->main_vbox;        break;
		case  5: RETVAL = fs->ok_button;        break;
		case  6: RETVAL = fs->cancel_button;    break;
		case  7: RETVAL = fs->help_button;      break;
		case  8: RETVAL = fs->history_pulldown; break;
		case  9: RETVAL = fs->history_menu;     break;
		case 10: RETVAL = fs->fileop_dialog;    break;
		case 11: RETVAL = fs->fileop_entry;     break;
		case 12: RETVAL = fs->fileop_c_dir;     break;
		case 13: RETVAL = fs->fileop_del_file;  break;
		case 14: RETVAL = fs->fileop_ren_file;  break;
		case 15: RETVAL = fs->button_area;      break;
		case 16: RETVAL = fs->action_area;      break;
		default:
			RETVAL = NULL;
			g_assert_not_reached ();
	}
#line 212 "xs\\GtkFileSelection.c"
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileSelection_fileop_file); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_fileop_file)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fs");
    {
	GtkFileSelection*	fs = SvGtkFileSelection (ST(0))
;
	gchar *	RETVAL;
#line 79 "xs\\\\GtkFileSelection.xs"
	RETVAL = fs->fileop_file;
#line 232 "xs\\GtkFileSelection.c"
	ST(0) = sv_newmortal();
	/* same as newSVGChar(), but not in a function */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileSelection_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, title");
    {
	const gchar *	title;
	GtkWidget *	RETVAL;

	/* same as SvGChar(), but not in a function */
	sv_utf8_upgrade (ST(1));
	title = (const gchar *)SvPV_nolen (ST(1))
;

	RETVAL = gtk_file_selection_new(title);
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileSelection_set_filename); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_set_filename)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filesel, filename");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
	GPerlFilename	filename = (GPerlFilename) gperl_filename_from_sv (ST(1))
;

	gtk_file_selection_set_filename(filesel, filename);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileSelection_complete); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_complete)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filesel, pattern");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
	const gchar *	pattern;

	/* same as SvGChar(), but not in a function */
	sv_utf8_upgrade (ST(1));
	pattern = (const gchar *)SvPV_nolen (ST(1))
;

	gtk_file_selection_complete(filesel, pattern);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileSelection_show_fileop_buttons); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_show_fileop_buttons)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filesel");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;

	gtk_file_selection_show_fileop_buttons(filesel);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileSelection_hide_fileop_buttons); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_hide_fileop_buttons)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filesel");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;

	gtk_file_selection_hide_fileop_buttons(filesel);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileSelection_set_select_multiple); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_set_select_multiple)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "filesel, select_multiple");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
	gboolean	select_multiple = (bool)SvTRUE(ST(1))
;

	gtk_file_selection_set_select_multiple(filesel, select_multiple);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__FileSelection_get_select_multiple); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_get_select_multiple)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filesel");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
	gboolean	RETVAL;

	RETVAL = gtk_file_selection_get_select_multiple(filesel);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileSelection_get_filename); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_get_filename)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filesel");
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
	GPerlFilename_const	RETVAL;

	RETVAL = gtk_file_selection_get_filename(filesel);
	ST(0) = sv_newmortal();
	sv_setsv (ST(0), sv_2mortal (gperl_sv_from_filename (RETVAL)));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__FileSelection_get_selections); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__FileSelection_get_selections)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "filesel");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	GtkFileSelection *	filesel = SvGtkFileSelection (ST(0))
;
#line 135 "xs\\\\GtkFileSelection.xs"
	int      i;
	gchar ** rets;
#line 407 "xs\\GtkFileSelection.c"
#line 138 "xs\\\\GtkFileSelection.xs"
	rets = gtk_file_selection_get_selections(filesel);
	for (i = 0; rets[i] != NULL; i++)
		XPUSHs (sv_2mortal (gperl_sv_from_filename (rets[i])));
	g_strfreev(rets);
#line 413 "xs\\GtkFileSelection.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Gtk2__FileSelection); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Gtk2__FileSelection)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

    {
        CV * cv;

        cv = newXS("Gtk2::FileSelection::dir_list", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 0;
        cv = newXS("Gtk2::FileSelection::history_pulldown", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 8;
        cv = newXS("Gtk2::FileSelection::fileop_entry", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 11;
        cv = newXS("Gtk2::FileSelection::main_vbox", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 4;
        cv = newXS("Gtk2::FileSelection::fileop_del_file", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 13;
        cv = newXS("Gtk2::FileSelection::fileop_c_dir", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 12;
        cv = newXS("Gtk2::FileSelection::fileop_dialog", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 10;
        cv = newXS("Gtk2::FileSelection::fileop_ren_file", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 14;
        cv = newXS("Gtk2::FileSelection::file_list", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 1;
        cv = newXS("Gtk2::FileSelection::selection_text", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 3;
        cv = newXS("Gtk2::FileSelection::history_menu", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 9;
        cv = newXS("Gtk2::FileSelection::ok_button", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 5;
        cv = newXS("Gtk2::FileSelection::action_area", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 16;
        cv = newXS("Gtk2::FileSelection::cancel_button", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 6;
        cv = newXS("Gtk2::FileSelection::selection_entry", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 2;
        cv = newXS("Gtk2::FileSelection::help_button", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 7;
        cv = newXS("Gtk2::FileSelection::button_area", XS_Gtk2__FileSelection_dir_list, file);
        XSANY.any_i32 = 15;
        newXS("Gtk2::FileSelection::fileop_file", XS_Gtk2__FileSelection_fileop_file, file);
        newXS("Gtk2::FileSelection::new", XS_Gtk2__FileSelection_new, file);
        newXS("Gtk2::FileSelection::set_filename", XS_Gtk2__FileSelection_set_filename, file);
        newXS("Gtk2::FileSelection::complete", XS_Gtk2__FileSelection_complete, file);
        newXS("Gtk2::FileSelection::show_fileop_buttons", XS_Gtk2__FileSelection_show_fileop_buttons, file);
        newXS("Gtk2::FileSelection::hide_fileop_buttons", XS_Gtk2__FileSelection_hide_fileop_buttons, file);
        newXS("Gtk2::FileSelection::set_select_multiple", XS_Gtk2__FileSelection_set_select_multiple, file);
        newXS("Gtk2::FileSelection::get_select_multiple", XS_Gtk2__FileSelection_get_select_multiple, file);
        newXS("Gtk2::FileSelection::get_filename", XS_Gtk2__FileSelection_get_filename, file);
        newXS("Gtk2::FileSelection::get_selections", XS_Gtk2__FileSelection_get_selections, file);
    }
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

