/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkPrintContext.xs. Do not edit this file, edit GtkPrintContext.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\GtkPrintContext.xs"
/*
 * Copyright (c) 2006 by the gtk2-perl team (see the file AUTHORS)
 *
 * Licensed under the LGPL, see LICENSE file for more information.
 *
 * $Id$
 */

#include "gtk2perl.h"
#include <cairo-perl.h>

#line 22 "xs\\GtkPrintContext.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 164 "xs\\GtkPrintContext.c"

XS_EUPXS(XS_Gtk2__PrintContext_get_cairo_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_cairo_context)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	cairo_t *	RETVAL;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_cairo_context(context);
	ST(0) = newSVCairo (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_page_setup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_page_setup)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	GtkPageSetup *	RETVAL;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_page_setup(context);
	ST(0) = newSVGtkPageSetup (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_width); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_width)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	gdouble	RETVAL;
	dXSTARG;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_width(context);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_height); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_height)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	gdouble	RETVAL;
	dXSTARG;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_height(context);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_dpi_x); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_dpi_x)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	gdouble	RETVAL;
	dXSTARG;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_dpi_x(context);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_dpi_y); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_dpi_y)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	gdouble	RETVAL;
	dXSTARG;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_dpi_y(context);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_get_pango_fontmap); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_pango_fontmap)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	PangoFontMap *	RETVAL;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_get_pango_fontmap(context);
	ST(0) = newSVPangoFontMap (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_create_pango_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_create_pango_context)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	PangoContext_noinc *	RETVAL;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_create_pango_context(context);
	ST(0) = newSVPangoContext_noinc (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_create_pango_layout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_create_pango_layout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	PangoLayout_noinc *	RETVAL;
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;

	RETVAL = gtk_print_context_create_pango_layout(context);
	ST(0) = newSVPangoLayout_noinc (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__PrintContext_set_cairo_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_set_cairo_context)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "context, cr, dpi_x, dpi_y");
    {
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;
	cairo_t *	cr = SvCairo (ST(1))
;
	double	dpi_x = (double)SvNV(ST(2))
;
	double	dpi_y = (double)SvNV(ST(3))
;

	gtk_print_context_set_cairo_context(context, cr, dpi_x, dpi_y);
    }
    XSRETURN_EMPTY;
}

#if GTK_CHECK_VERSION (2, 20, 0)
#define XSubPPtmpAAAA 1


XS_EUPXS(XS_Gtk2__PrintContext_get_hard_margins); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__PrintContext_get_hard_margins)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 46 "xs\\\\GtkPrintContext.xs"
	gdouble top, bottom, left, right;
#line 373 "xs\\GtkPrintContext.c"
	GtkPrintContext *	context = SvGtkPrintContext (ST(0))
;
#line 48 "xs\\\\GtkPrintContext.xs"
	if (!gtk_print_context_get_hard_margins (context, &top, &bottom, &left, &right))
		XSRETURN_EMPTY;
	EXTEND (SP, 4);
	PUSHs (sv_2mortal (newSVnv (top)));
	PUSHs (sv_2mortal (newSVnv (bottom)));
	PUSHs (sv_2mortal (newSVnv (left)));
	PUSHs (sv_2mortal (newSVnv (right)));
#line 384 "xs\\GtkPrintContext.c"
	PUTBACK;
	return;
    }
}

#endif /* 2.20 */
#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Gtk2__PrintContext); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Gtk2__PrintContext)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Gtk2::PrintContext::get_cairo_context", XS_Gtk2__PrintContext_get_cairo_context, file);
        newXS("Gtk2::PrintContext::get_page_setup", XS_Gtk2__PrintContext_get_page_setup, file);
        newXS("Gtk2::PrintContext::get_width", XS_Gtk2__PrintContext_get_width, file);
        newXS("Gtk2::PrintContext::get_height", XS_Gtk2__PrintContext_get_height, file);
        newXS("Gtk2::PrintContext::get_dpi_x", XS_Gtk2__PrintContext_get_dpi_x, file);
        newXS("Gtk2::PrintContext::get_dpi_y", XS_Gtk2__PrintContext_get_dpi_y, file);
        newXS("Gtk2::PrintContext::get_pango_fontmap", XS_Gtk2__PrintContext_get_pango_fontmap, file);
        newXS("Gtk2::PrintContext::create_pango_context", XS_Gtk2__PrintContext_create_pango_context, file);
        newXS("Gtk2::PrintContext::create_pango_layout", XS_Gtk2__PrintContext_create_pango_layout, file);
        newXS("Gtk2::PrintContext::set_cairo_context", XS_Gtk2__PrintContext_set_cairo_context, file);
#if XSubPPtmpAAAA
        newXS("Gtk2::PrintContext::get_hard_margins", XS_Gtk2__PrintContext_get_hard_margins, file);
#endif

    /* Initialisation Section */

#if XSubPPtmpAAAA
#endif
#line 429 "xs\\GtkPrintContext.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

