/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkSpinButton.xs. Do not edit this file, edit GtkSpinButton.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\GtkSpinButton.xs"
/*
 * Copyright (c) 2003 by the gtk2-perl team (see the file AUTHORS)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the 
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330, 
 * Boston, MA  02111-1307  USA.
 *
 * $Id$
 */

#include "gtk2perl.h"

#line 34 "xs\\GtkSpinButton.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 176 "xs\\GtkSpinButton.c"

XS_EUPXS(XS_Gtk2__SpinButton_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_new)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "class, adjustment, climb_rate, digits");
    {
	GtkAdjustment *	adjustment = SvGtkAdjustment (ST(1))
;
	gdouble	climb_rate = (double)SvNV(ST(2))
;
	guint	digits = (guint)SvUV(ST(3))
;
	GtkWidget *	RETVAL;

	RETVAL = gtk_spin_button_new(adjustment, climb_rate, digits);
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_new_with_range); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_new_with_range)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "class, min, max, step");
    {
	gdouble	min = (double)SvNV(ST(1))
;
	gdouble	max = (double)SvNV(ST(2))
;
	gdouble	step = (double)SvNV(ST(3))
;
	GtkWidget *	RETVAL;

	RETVAL = gtk_spin_button_new_with_range(min, max, step);
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_configure); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_configure)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "spin_button, adjustment, climb_rate, digits");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkAdjustment *	adjustment = SvGtkAdjustment (ST(1))
;
	gdouble	climb_rate = (double)SvNV(ST(2))
;
	guint	digits = (guint)SvUV(ST(3))
;

	gtk_spin_button_configure(spin_button, adjustment, climb_rate, digits);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_set_adjustment); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_adjustment)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, adjustment");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkAdjustment *	adjustment = SvGtkAdjustment (ST(1))
;

	gtk_spin_button_set_adjustment(spin_button, adjustment);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_set_digits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_digits)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, digits");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	guint	digits = (guint)SvUV(ST(1))
;

	gtk_spin_button_set_digits(spin_button, digits);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_digits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_digits)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	guint	RETVAL;
	dXSTARG;

	RETVAL = gtk_spin_button_get_digits(spin_button);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_set_increments); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_increments)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "spin_button, step, page");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	step = (double)SvNV(ST(1))
;
	gdouble	page = (double)SvNV(ST(2))
;

	gtk_spin_button_set_increments(spin_button, step, page);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_increments); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_increments)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	step;
	gdouble	page;

	gtk_spin_button_get_increments(spin_button, &step, &page);
	XSprePUSH;	EXTEND(SP,2);
	PUSHs(sv_newmortal());
	sv_setnv(ST(0), (double)step);
	PUSHs(sv_newmortal());
	sv_setnv(ST(1), (double)page);
    }
    XSRETURN(2);
}


XS_EUPXS(XS_Gtk2__SpinButton_set_range); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_range)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "spin_button, min, max");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	min = (double)SvNV(ST(1))
;
	gdouble	max = (double)SvNV(ST(2))
;

	gtk_spin_button_set_range(spin_button, min, max);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_range); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_range)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	min;
	gdouble	max;

	gtk_spin_button_get_range(spin_button, &min, &max);
	XSprePUSH;	EXTEND(SP,2);
	PUSHs(sv_newmortal());
	sv_setnv(ST(0), (double)min);
	PUSHs(sv_newmortal());
	sv_setnv(ST(1), (double)max);
    }
    XSRETURN(2);
}


XS_EUPXS(XS_Gtk2__SpinButton_get_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_value)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	RETVAL;
	dXSTARG;

	RETVAL = gtk_spin_button_get_value(spin_button);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_get_value_as_int); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_value_as_int)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gint	RETVAL;
	dXSTARG;

	RETVAL = gtk_spin_button_get_value_as_int(spin_button);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_set_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_value)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, value");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gdouble	value = (double)SvNV(ST(1))
;

	gtk_spin_button_set_value(spin_button, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_set_update_policy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_update_policy)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, policy");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkSpinButtonUpdatePolicy	policy = SvGtkSpinButtonUpdatePolicy (ST(1))
;

	gtk_spin_button_set_update_policy(spin_button, policy);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_update_policy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_update_policy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkSpinButtonUpdatePolicy	RETVAL;

	RETVAL = gtk_spin_button_get_update_policy(spin_button);
	ST(0) = newSVGtkSpinButtonUpdatePolicy (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_set_numeric); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_numeric)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, numeric");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	numeric = (bool)SvTRUE(ST(1))
;

	gtk_spin_button_set_numeric(spin_button, numeric);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_numeric); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_numeric)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	RETVAL;

	RETVAL = gtk_spin_button_get_numeric(spin_button);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_spin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_spin)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "spin_button, direction, increment");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkSpinType	direction = SvGtkSpinType (ST(1))
;
	gdouble	increment = (double)SvNV(ST(2))
;

	gtk_spin_button_spin(spin_button, direction, increment);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_set_wrap); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_wrap)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, wrap");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	wrap = (bool)SvTRUE(ST(1))
;

	gtk_spin_button_set_wrap(spin_button, wrap);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_wrap); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_wrap)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	RETVAL;

	RETVAL = gtk_spin_button_get_wrap(spin_button);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_set_snap_to_ticks); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_set_snap_to_ticks)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "spin_button, snap_to_ticks");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	snap_to_ticks = (bool)SvTRUE(ST(1))
;

	gtk_spin_button_set_snap_to_ticks(spin_button, snap_to_ticks);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_snap_to_ticks); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_snap_to_ticks)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	gboolean	RETVAL;

	RETVAL = gtk_spin_button_get_snap_to_ticks(spin_button);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__SpinButton_update); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_update)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;

	gtk_spin_button_update(spin_button);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__SpinButton_get_adjustment); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__SpinButton_get_adjustment)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "spin_button");
    {
	GtkSpinButton *	spin_button = SvGtkSpinButton (ST(0))
;
	GtkAdjustment *	RETVAL;

	RETVAL = gtk_spin_button_get_adjustment(spin_button);
	ST(0) = newSVGtkAdjustment (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Gtk2__SpinButton); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Gtk2__SpinButton)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Gtk2::SpinButton::new", XS_Gtk2__SpinButton_new, file);
        newXS("Gtk2::SpinButton::new_with_range", XS_Gtk2__SpinButton_new_with_range, file);
        newXS("Gtk2::SpinButton::configure", XS_Gtk2__SpinButton_configure, file);
        newXS("Gtk2::SpinButton::set_adjustment", XS_Gtk2__SpinButton_set_adjustment, file);
        newXS("Gtk2::SpinButton::set_digits", XS_Gtk2__SpinButton_set_digits, file);
        newXS("Gtk2::SpinButton::get_digits", XS_Gtk2__SpinButton_get_digits, file);
        newXS("Gtk2::SpinButton::set_increments", XS_Gtk2__SpinButton_set_increments, file);
        newXS("Gtk2::SpinButton::get_increments", XS_Gtk2__SpinButton_get_increments, file);
        newXS("Gtk2::SpinButton::set_range", XS_Gtk2__SpinButton_set_range, file);
        newXS("Gtk2::SpinButton::get_range", XS_Gtk2__SpinButton_get_range, file);
        newXS("Gtk2::SpinButton::get_value", XS_Gtk2__SpinButton_get_value, file);
        newXS("Gtk2::SpinButton::get_value_as_int", XS_Gtk2__SpinButton_get_value_as_int, file);
        newXS("Gtk2::SpinButton::set_value", XS_Gtk2__SpinButton_set_value, file);
        newXS("Gtk2::SpinButton::set_update_policy", XS_Gtk2__SpinButton_set_update_policy, file);
        newXS("Gtk2::SpinButton::get_update_policy", XS_Gtk2__SpinButton_get_update_policy, file);
        newXS("Gtk2::SpinButton::set_numeric", XS_Gtk2__SpinButton_set_numeric, file);
        newXS("Gtk2::SpinButton::get_numeric", XS_Gtk2__SpinButton_get_numeric, file);
        newXS("Gtk2::SpinButton::spin", XS_Gtk2__SpinButton_spin, file);
        newXS("Gtk2::SpinButton::set_wrap", XS_Gtk2__SpinButton_set_wrap, file);
        newXS("Gtk2::SpinButton::get_wrap", XS_Gtk2__SpinButton_get_wrap, file);
        newXS("Gtk2::SpinButton::set_snap_to_ticks", XS_Gtk2__SpinButton_set_snap_to_ticks, file);
        newXS("Gtk2::SpinButton::get_snap_to_ticks", XS_Gtk2__SpinButton_get_snap_to_ticks, file);
        newXS("Gtk2::SpinButton::update", XS_Gtk2__SpinButton_update, file);
        newXS("Gtk2::SpinButton::get_adjustment", XS_Gtk2__SpinButton_get_adjustment, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

