/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkToolPalette.xs. Do not edit this file, edit GtkToolPalette.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\GtkToolPalette.xs"
/*
 * Copyright (c) 2010 by the gtk2-perl team (see the file AUTHORS)
 *
 * Licensed under the LGPL, see LICENSE file for more information.
 *
 * $Id$
 */

#include "gtk2perl.h"

#line 21 "xs\\GtkToolPalette.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 163 "xs\\GtkToolPalette.c"

XS_EUPXS(XS_Gtk2__ToolPalette_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	GtkWidget *	RETVAL;

	RETVAL = gtk_tool_palette_new(/* void */);
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_exclusive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_exclusive)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, group");
    {
	gboolean	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;

	RETVAL = gtk_tool_palette_get_exclusive(palette, group);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_exclusive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_exclusive)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "palette, group, exclusive");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;
	gboolean	exclusive = (bool)SvTRUE(ST(2))
;

	gtk_tool_palette_set_exclusive(palette, group, exclusive);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_expand); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_expand)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, group");
    {
	gboolean	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;

	RETVAL = gtk_tool_palette_get_expand(palette, group);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_expand); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_expand)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "palette, group, expand");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;
	gboolean	expand = (bool)SvTRUE(ST(2))
;

	gtk_tool_palette_set_expand(palette, group, expand);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_group_position); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_group_position)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, group");
    {
	gint	RETVAL;
	dXSTARG;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;

	RETVAL = gtk_tool_palette_get_group_position(palette, group);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_group_position); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_group_position)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "palette, group, position");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolItemGroup *	group = SvGtkToolItemGroup (ST(1))
;
	gint	position = (gint)SvIV(ST(2))
;

	gtk_tool_palette_set_group_position(palette, group, position);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_icon_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_icon_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkIconSize	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	RETVAL = gtk_tool_palette_get_icon_size(palette);
	ST(0) = newSVGtkIconSize (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_icon_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_icon_size)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, icon_size");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkIconSize	icon_size = SvGtkIconSize (ST(1))
;

	gtk_tool_palette_set_icon_size(palette, icon_size);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_unset_icon_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_unset_icon_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	gtk_tool_palette_unset_icon_size(palette);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_style); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_style)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkToolbarStyle	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	RETVAL = gtk_tool_palette_get_style(palette);
	ST(0) = newSVGtkToolbarStyle (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_style); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_style)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, style");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolbarStyle	style = SvGtkToolbarStyle (ST(1))
;

	gtk_tool_palette_set_style(palette, style);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_unset_style); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_unset_style)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	gtk_tool_palette_unset_style(palette);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_add_drag_dest); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_add_drag_dest)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "palette, widget, flags, targets, actions");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkWidget *	widget = SvGtkWidget (ST(1))
;
	GtkDestDefaults	flags = SvGtkDestDefaults (ST(2))
;
	GtkToolPaletteDragTargets	targets = SvGtkToolPaletteDragTargets (ST(3))
;
	GdkDragAction	actions = SvGdkDragAction (ST(4))
;

	gtk_tool_palette_add_drag_dest(palette, widget, flags, targets, actions);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_item); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_item)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, selection");
    {
	GtkWidget *	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	const GtkSelectionData *	selection = SvGtkSelectionData (ST(1))
;

	RETVAL = gtk_tool_palette_get_drag_item(palette, selection);
	ST(0) = newSVGtkWidget (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_target_group); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_target_group)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	GtkTargetEntry *	RETVAL;
#line 50 "xs\\\\GtkToolPalette.xs"
	RETVAL = (GtkTargetEntry*) gtk_tool_palette_get_drag_target_group ();
#line 466 "xs\\GtkToolPalette.c"
	ST(0) = newSVGtkTargetEntry (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_target_item); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_drag_target_item)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	GtkTargetEntry *	RETVAL;
#line 58 "xs\\\\GtkToolPalette.xs"
	RETVAL = (GtkTargetEntry*) gtk_tool_palette_get_drag_target_item ();
#line 484 "xs\\GtkToolPalette.c"
	ST(0) = newSVGtkTargetEntry (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_drop_group); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_drop_group)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "palette, x, y");
    {
	GtkToolItemGroup_ornull *	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	gint	x = (gint)SvIV(ST(1))
;
	gint	y = (gint)SvIV(ST(2))
;

	RETVAL = gtk_tool_palette_get_drop_group(palette, x, y);
	ST(0) = newSVGtkToolItemGroup_ornull (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_drop_item); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_drop_item)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "palette, x, y");
    {
	GtkToolItem_ornull *	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	gint	x = (gint)SvIV(ST(1))
;
	gint	y = (gint)SvIV(ST(2))
;

	RETVAL = gtk_tool_palette_get_drop_item(palette, x, y);
	ST(0) = newSVGtkToolItem_ornull (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_set_drag_source); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_set_drag_source)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "palette, targets");
    {
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;
	GtkToolPaletteDragTargets	targets = SvGtkToolPaletteDragTargets (ST(1))
;

	gtk_tool_palette_set_drag_source(palette, targets);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_hadjustment); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_hadjustment)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkAdjustment *	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	RETVAL = gtk_tool_palette_get_hadjustment(palette);
	ST(0) = newSVGtkAdjustment (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk2__ToolPalette_get_vadjustment); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk2__ToolPalette_get_vadjustment)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "palette");
    {
	GtkAdjustment *	RETVAL;
	GtkToolPalette *	palette = SvGtkToolPalette (ST(0))
;

	RETVAL = gtk_tool_palette_get_vadjustment(palette);
	ST(0) = newSVGtkAdjustment (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Gtk2__ToolPalette); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Gtk2__ToolPalette)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Gtk2::ToolPalette::new", XS_Gtk2__ToolPalette_new, file);
        newXS("Gtk2::ToolPalette::get_exclusive", XS_Gtk2__ToolPalette_get_exclusive, file);
        newXS("Gtk2::ToolPalette::set_exclusive", XS_Gtk2__ToolPalette_set_exclusive, file);
        newXS("Gtk2::ToolPalette::get_expand", XS_Gtk2__ToolPalette_get_expand, file);
        newXS("Gtk2::ToolPalette::set_expand", XS_Gtk2__ToolPalette_set_expand, file);
        newXS("Gtk2::ToolPalette::get_group_position", XS_Gtk2__ToolPalette_get_group_position, file);
        newXS("Gtk2::ToolPalette::set_group_position", XS_Gtk2__ToolPalette_set_group_position, file);
        newXS("Gtk2::ToolPalette::get_icon_size", XS_Gtk2__ToolPalette_get_icon_size, file);
        newXS("Gtk2::ToolPalette::set_icon_size", XS_Gtk2__ToolPalette_set_icon_size, file);
        newXS("Gtk2::ToolPalette::unset_icon_size", XS_Gtk2__ToolPalette_unset_icon_size, file);
        newXS("Gtk2::ToolPalette::get_style", XS_Gtk2__ToolPalette_get_style, file);
        newXS("Gtk2::ToolPalette::set_style", XS_Gtk2__ToolPalette_set_style, file);
        newXS("Gtk2::ToolPalette::unset_style", XS_Gtk2__ToolPalette_unset_style, file);
        newXS("Gtk2::ToolPalette::add_drag_dest", XS_Gtk2__ToolPalette_add_drag_dest, file);
        newXS("Gtk2::ToolPalette::get_drag_item", XS_Gtk2__ToolPalette_get_drag_item, file);
        newXS("Gtk2::ToolPalette::get_drag_target_group", XS_Gtk2__ToolPalette_get_drag_target_group, file);
        newXS("Gtk2::ToolPalette::get_drag_target_item", XS_Gtk2__ToolPalette_get_drag_target_item, file);
        newXS("Gtk2::ToolPalette::get_drop_group", XS_Gtk2__ToolPalette_get_drop_group, file);
        newXS("Gtk2::ToolPalette::get_drop_item", XS_Gtk2__ToolPalette_get_drop_item, file);
        newXS("Gtk2::ToolPalette::set_drag_source", XS_Gtk2__ToolPalette_set_drag_source, file);
        newXS("Gtk2::ToolPalette::get_hadjustment", XS_Gtk2__ToolPalette_get_hadjustment, file);
        newXS("Gtk2::ToolPalette::get_vadjustment", XS_Gtk2__ToolPalette_get_vadjustment, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

