--- #YAML:1.0
name:               Pango
version:            1.223
abstract:           Layout and render international text
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    Cairo:                1.000
    ExtUtils::Depends:    0.300
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1.030
    Glib:                 1.220
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cairo:                1.000
    ExtUtils::Depends:    0.300
    ExtUtils::PkgConfig:  1.030
    Glib:                 1.220
no_index:
    directory:
        - t
        - inc
    file:
        - xs/Pango.xs
        - xs/PangoAttributes.xs
        - xs/PangoContext.xs
        - xs/PangoFont.xs
        - xs/PangoFontset.xs
        - xs/PangoFontMap.xs
        - xs/PangoLayout.xs
        - xs/PangoRenderer.xs
        - xs/PangoScript.xs
        - xs/PangoTabs.xs
        - xs/PangoTypes.xs
        - xs/PangoCairo.xs
        - xs/PangoGravity.xs
        - xs/PangoMatrix.xs
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
