---
abstract: 'Perl interface to the 2.x series of the Gimp Toolkit library'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  Cairo: 1.000
  ExtUtils::Depends: 0.300
  ExtUtils::MakeMaker: 0
  ExtUtils::PkgConfig: 1.030
  Glib: 1.240
  Pango: 1.220
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk2
no_index:
  directory:
    - t
    - inc
    - tools
    - xs
  file:
    - Makefile.PL
    - gtk-demo/main.pl
requires:
  Cairo: 1.000
  ExtUtils::Depends: 0.300
  ExtUtils::PkgConfig: 1.030
  Glib: 1.240
  Pango: 1.220
version: 1.246
