/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of PangoCairo.xs. Do not edit this file, edit PangoCairo.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "xs\\\\PangoCairo.xs"
/*
 * Copyright (c) 2005 by the gtk2-perl team (see the file AUTHORS)
 *
 * Licensed under the LGPL, see LICENSE file for more information.
 */

#include "pango-perl.h"
#include <cairo-perl.h>
#include <gperl_marshal.h>

/* ------------------------------------------------------------------------- */

#if PANGO_CHECK_VERSION (1, 17, 0)

static void
gtk2perl_pango_cairo_shape_renderer_func (cairo_t        *cr,
					  PangoAttrShape *attr,
					  gboolean        do_path,
					  gpointer        data)
{
	GPerlCallback *callback = (GPerlCallback *) data;
	dGPERL_CALLBACK_MARSHAL_SP;

	GPERL_CALLBACK_MARSHAL_INIT (callback);

	ENTER;
	SAVETMPS;

	PUSHMARK (SP);

	EXTEND (SP, 3);
	PUSHs (sv_2mortal (newSVCairo (cr)));
	PUSHs (sv_2mortal (newSVPangoAttribute (attr)));
	PUSHs (sv_2mortal (newSVuv (do_path)));
	if (callback->data)
		XPUSHs (sv_2mortal (newSVsv (callback->data)));

	PUTBACK;

	call_sv (callback->func, G_DISCARD);

	FREETMPS;
	LEAVE;
}

#endif

/* ------------------------------------------------------------------------- */

#line 60 "xs\\PangoCairo.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 202 "xs\\PangoCairo.c"

XS_EUPXS(XS_Pango__Cairo__FontMap_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	PangoFontMap_noinc *	RETVAL;

	RETVAL = pango_cairo_font_map_new(/* void */);
	ST(0) = newSVPangoFontMap_noinc (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo__FontMap_get_default); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_get_default)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	PangoFontMap *	RETVAL;

	RETVAL = pango_cairo_font_map_get_default(/* void */);
	ST(0) = newSVPangoFontMap (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo__FontMap_set_resolution); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_set_resolution)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fontmap, dpi");
    {
	PangoCairoFontMap *	fontmap = SvPangoCairoFontMap (ST(0))
;
	double	dpi = (double)SvNV(ST(1))
;

	pango_cairo_font_map_set_resolution(fontmap, dpi);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo__FontMap_get_resolution); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_get_resolution)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fontmap");
    {
	double	RETVAL;
	dXSTARG;
	PangoCairoFontMap *	fontmap = SvPangoCairoFontMap (ST(0))
;

	RETVAL = pango_cairo_font_map_get_resolution(fontmap);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo__FontMap_create_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_create_context)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fontmap");
    {
#line 70 "xs\\\\PangoCairo.xs"
	PangoContext *context;
	HV *stash;
#line 285 "xs\\PangoCairo.c"
	SV *	RETVAL;
	PangoCairoFontMap *	fontmap = SvPangoCairoFontMap (ST(0))
;
#line 73 "xs\\\\PangoCairo.xs"
	context = pango_cairo_font_map_create_context (fontmap);
	if (!context)
		XSRETURN_UNDEF;
	RETVAL = newSVPangoContext (context);
	stash = gv_stashpv ("Pango::Cairo::Context", TRUE);
	sv_bless (RETVAL, stash);
#line 296 "xs\\PangoCairo.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#if PANGO_CHECK_VERSION (1, 18, 0)
#define XSubPPtmpAAAA 1


XS_EUPXS(XS_Pango__Cairo__FontMap_new_for_font_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_new_for_font_type)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, fonttype");
    {
	PangoFontMap_noinc *	RETVAL;
	cairo_font_type_t	fonttype = SvCairoFontType (ST(1))
;

	RETVAL = pango_cairo_font_map_new_for_font_type(fonttype);
	ST(0) = newSVPangoFontMap_noinc (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo__FontMap_get_font_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__FontMap_get_font_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fontmap");
    {
	cairo_font_type_t	RETVAL;
	PangoCairoFontMap *	fontmap = SvPangoCairoFontMap (ST(0))
;

	RETVAL = pango_cairo_font_map_get_font_type(fontmap);
	ST(0) = newSVCairoFontType (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#endif
#if PANGO_CHECK_VERSION (1, 18, 0)
#define XSubPPtmpAAAB 1


XS_EUPXS(XS_Pango__Cairo__Font_get_scaled_font); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Font_get_scaled_font)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "font");
    {
	cairo_scaled_font_t *	RETVAL;
	PangoCairoFont *	font = SvPangoCairoFont (ST(0))
;

	RETVAL = pango_cairo_font_get_scaled_font(font);
	ST(0) = newSVCairoScaledFont (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#endif

XS_EUPXS(XS_Pango__Cairo_update_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_update_context)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, context");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoContext *	context = SvPangoContext (ST(1))
;

	pango_cairo_update_context(cr, context);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_create_layout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_create_layout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cr");
    {
	PangoLayout *	RETVAL;
	cairo_t *	cr = SvCairo (ST(0))
;

	RETVAL = pango_cairo_create_layout(cr);
	ST(0) = newSVPangoLayout (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo_update_layout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_update_layout)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, layout");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoLayout *	layout = SvPangoLayout (ST(1))
;

	pango_cairo_update_layout(cr, layout);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_show_glyph_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_show_glyph_string)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "cr, font, glyphs");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoFont *	font = SvPangoFont (ST(1))
;
	PangoGlyphString *	glyphs = SvPangoGlyphString (ST(2))
;

	pango_cairo_show_glyph_string(cr, font, glyphs);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_show_layout_line); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_show_layout_line)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, line");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoLayoutLine *	line = SvPangoLayoutLine (ST(1))
;

	pango_cairo_show_layout_line(cr, line);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_show_layout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_show_layout)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, layout");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoLayout *	layout = SvPangoLayout (ST(1))
;

	pango_cairo_show_layout(cr, layout);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_glyph_string_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_glyph_string_path)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "cr, font, glyphs");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoFont *	font = SvPangoFont (ST(1))
;
	PangoGlyphString *	glyphs = SvPangoGlyphString (ST(2))
;

	pango_cairo_glyph_string_path(cr, font, glyphs);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_layout_line_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_layout_line_path)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, line");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoLayoutLine *	line = SvPangoLayoutLine (ST(1))
;

	pango_cairo_layout_line_path(cr, line);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_layout_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_layout_path)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cr, layout");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	PangoLayout *	layout = SvPangoLayout (ST(1))
;

	pango_cairo_layout_path(cr, layout);
    }
    XSRETURN_EMPTY;
}

#if PANGO_CHECK_VERSION (1, 14, 0)
#define XSubPPtmpAAAC 1


XS_EUPXS(XS_Pango__Cairo_show_error_underline); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_show_error_underline)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "cr, x, y, width, height");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	double	x = (double)SvNV(ST(1))
;
	double	y = (double)SvNV(ST(2))
;
	double	width = (double)SvNV(ST(3))
;
	double	height = (double)SvNV(ST(4))
;

	pango_cairo_show_error_underline(cr, x, y, width, height);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo_error_underline_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo_error_underline_path)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "cr, x, y, width, height");
    {
	cairo_t *	cr = SvCairo (ST(0))
;
	double	x = (double)SvNV(ST(1))
;
	double	y = (double)SvNV(ST(2))
;
	double	width = (double)SvNV(ST(3))
;
	double	height = (double)SvNV(ST(4))
;

	pango_cairo_error_underline_path(cr, x, y, width, height);
    }
    XSRETURN_EMPTY;
}

#endif

XS_EUPXS(XS_Pango__Cairo__Context_set_font_options); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Context_set_font_options)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "context, options");
    {
	PangoContext *	context = SvPangoContext (ST(0))
;
	const cairo_font_options_t *	options = SvCairoFontOptions (ST(1))
;

	pango_cairo_context_set_font_options(context, options);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo__Context_get_font_options); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Context_get_font_options)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	const cairo_font_options_t *	RETVAL;
	PangoContext *	context = SvPangoContext (ST(0))
;
#line 187 "xs\\\\PangoCairo.xs"
	RETVAL = cairo_font_options_copy (
			pango_cairo_context_get_font_options (context));
#line 619 "xs\\PangoCairo.c"
	ST(0) = newSVCairoFontOptions (RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pango__Cairo__Context_set_resolution); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Context_set_resolution)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "context, dpi");
    {
	PangoContext *	context = SvPangoContext (ST(0))
;
	double	dpi = (double)SvNV(ST(1))
;

	pango_cairo_context_set_resolution(context, dpi);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pango__Cairo__Context_get_resolution); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Context_get_resolution)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	double	RETVAL;
	dXSTARG;
	PangoContext *	context = SvPangoContext (ST(0))
;

	RETVAL = pango_cairo_context_get_resolution(context);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

#if PANGO_CHECK_VERSION (1, 18, 0)
#define XSubPPtmpAAAD 1


XS_EUPXS(XS_Pango__Cairo__Context_set_shape_renderer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pango__Cairo__Context_set_shape_renderer)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 3)
       croak_xs_usage(cv,  "context, func=NULL, data=NULL");
    {
#line 208 "xs\\\\PangoCairo.xs"
	GPerlCallback *callback;
	GDestroyNotify dnotify;
#line 677 "xs\\PangoCairo.c"
	PangoContext *	context = SvPangoContext (ST(0))
;
	SV *	func;
	SV *	data;

	if (items < 2)
	    func = NULL;
	else {
	    func = ST(1)
;
	}

	if (items < 3)
	    data = NULL;
	else {
	    data = ST(2)
;
	}
#line 211 "xs\\\\PangoCairo.xs"
	if (gperl_sv_is_defined (func)) {
		callback = gperl_callback_new (func, data, 0, NULL, 0);
		dnotify = (GDestroyNotify) gperl_callback_destroy;
	} else {
		callback = NULL;
		dnotify = NULL;
	}
	pango_cairo_context_set_shape_renderer (
		context,
		gtk2perl_pango_cairo_shape_renderer_func,
		callback,
		dnotify);
#line 709 "xs\\PangoCairo.c"
    }
    XSRETURN_EMPTY;
}

#endif
#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Pango__Cairo); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Pango__Cairo)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Pango::Cairo::FontMap::new", XS_Pango__Cairo__FontMap_new, file);
        newXS("Pango::Cairo::FontMap::get_default", XS_Pango__Cairo__FontMap_get_default, file);
        newXS("Pango::Cairo::FontMap::set_resolution", XS_Pango__Cairo__FontMap_set_resolution, file);
        newXS("Pango::Cairo::FontMap::get_resolution", XS_Pango__Cairo__FontMap_get_resolution, file);
        newXS("Pango::Cairo::FontMap::create_context", XS_Pango__Cairo__FontMap_create_context, file);
#if XSubPPtmpAAAA
        newXS("Pango::Cairo::FontMap::new_for_font_type", XS_Pango__Cairo__FontMap_new_for_font_type, file);
        newXS("Pango::Cairo::FontMap::get_font_type", XS_Pango__Cairo__FontMap_get_font_type, file);
#endif
#if XSubPPtmpAAAB
        newXS("Pango::Cairo::Font::get_scaled_font", XS_Pango__Cairo__Font_get_scaled_font, file);
#endif
        newXS("Pango::Cairo::update_context", XS_Pango__Cairo_update_context, file);
        newXS("Pango::Cairo::create_layout", XS_Pango__Cairo_create_layout, file);
        newXS("Pango::Cairo::update_layout", XS_Pango__Cairo_update_layout, file);
        newXS("Pango::Cairo::show_glyph_string", XS_Pango__Cairo_show_glyph_string, file);
        newXS("Pango::Cairo::show_layout_line", XS_Pango__Cairo_show_layout_line, file);
        newXS("Pango::Cairo::show_layout", XS_Pango__Cairo_show_layout, file);
        newXS("Pango::Cairo::glyph_string_path", XS_Pango__Cairo_glyph_string_path, file);
        newXS("Pango::Cairo::layout_line_path", XS_Pango__Cairo_layout_line_path, file);
        newXS("Pango::Cairo::layout_path", XS_Pango__Cairo_layout_path, file);
#if XSubPPtmpAAAC
        newXS("Pango::Cairo::show_error_underline", XS_Pango__Cairo_show_error_underline, file);
        newXS("Pango::Cairo::error_underline_path", XS_Pango__Cairo_error_underline_path, file);
#endif
        newXS("Pango::Cairo::Context::set_font_options", XS_Pango__Cairo__Context_set_font_options, file);
        newXS("Pango::Cairo::Context::get_font_options", XS_Pango__Cairo__Context_get_font_options, file);
        newXS("Pango::Cairo::Context::set_resolution", XS_Pango__Cairo__Context_set_resolution, file);
        newXS("Pango::Cairo::Context::get_resolution", XS_Pango__Cairo__Context_get_resolution, file);
#if XSubPPtmpAAAD
        newXS("Pango::Cairo::Context::set_shape_renderer", XS_Pango__Cairo__Context_set_shape_renderer, file);
#endif

    /* Initialisation Section */

#if XSubPPtmpAAAA
#endif
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#line 166 "xs\\\\PangoCairo.xs"
	gperl_set_isa ("Pango::Cairo::Context", "Pango::Context");

#if XSubPPtmpAAAD
#endif
#line 781 "xs\\PangoCairo.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

